### ISSUE TITLE
MacOS window buttons

### ISSUE THREAD

**Issue by Uiniel** [Uiniel/zen-mods#24]
![image](https://github.com/user-attachments/assets/b6d8862a-8342-41c6-9ace-02e84db4baa8)
https://discord.com/channels/1088172780480114748/1316100064900284547/1318465309526724782

**Comment by Uiniel** [comment]
@madzn-dev I just realized `@media (-moz-platform: macos)` exists and I don't know how I forgot about it, but in theory with that it should be possible to fix the issue.

If you have time, could you maybe try the current dev version (see #15 for instructions)? I can't test it myself so I don't know if it actually fixes the issue.

**Comment by madzn-dev** [comment]
Thank you for the quick reply! I am unable to find my 'userChrome.css' file
on my MacBook files. I found the chrome.css file, inside the folder of this
zen mod. Should I create a 'userChrome.css' in zen profile root directory?
(profile/.../chrome/*) ? and then paste the contents of chrome.css?


madzn-dev

**Comment by madzn-dev** [comment]
I just tried it! and it seems to work! I am unable to reproduce the traffic lights misalignment. Kudos.

**Comment by MitchellBouwman** [comment]
@Uiniel Im having the same issue. I really like the mod (thanks for it!) but I cant minimize my window anymore. Looking forward for the update so I can enable the mod again.

**Comment by wunder-one** [comment]
Just wanted to note that the dev version fixed the issue for me. Not sure if this is helpful, as this is already marked as done.

**Comment by Uiniel** [comment]
Ok I pushed the update today. I originally planned to include it in the next big update, but that'll take longer as expected and this seems like a pressing issue.

**Comment by MitchellBouwman** [comment]
@Uiniel Is the update live? I reinstalled the plugin but still appears broken.

![Image](https://github.com/user-attachments/assets/10bff0d8-903d-467b-ac39-0e0e884c9d91)

**Comment by Uiniel** [comment]
- @MitchellBouwman my theme store pull request isn't merged yet probably just takes some time

**Comment by drewgallinger** [comment]
this is killing me

**Comment by mattmess1221** [comment]
This also happens on Linux with window buttons on the left.

**Comment by mattmess1221** [comment]
This selector should fix the issue, no `@media (-moz-platform: macos)` needed. At least on Linux.

https://github.com/Uiniel/zen-mods/blob/21470736055c89cca8e0accf7330cf253db0736f/sidebar-expand-on-hover/chrome.css#L24

```css
#zen-appcontent-navbar-container:has(#nav-bar>.titlebar-buttonbox-container:last-child) {
```

It only applies if the window buttons are the last element in its parent container (`toolbar#nav-bar`). On MacOS(?) and Linux with buttons on the left, it is the first element.

**Comment by Uiniel** [comment]
@mattmess1221 thank you so much for that code. I tried it on Linux once with buttons on the left (in gnome) and for me I didn't get the issue and that element didn't exist. And I didn't know that some other desktop environments where effected by this bug as well.

**Comment by Uiniel** [comment]
@mattmess1221 update is out, can you check if it's working now?

**Comment by mattmess1221** [comment]
Yes, it's working.

![Image](https://github.com/user-attachments/assets/388ea431-3617-4c43-83ee-0b4749a4b3a4)

(Ignore the essentials being stretched, it's #21)

**Comment by MitchellBouwman** [comment]
Works great, thanks for your effort @Uiniel! ;)
